### PR TITLE
Ekemini02

### PR DESCRIPTION
**Pull request by EkeminiImeOtu**
Trying to get it right, please have you seen my attached file? datetime.py

### CODE REVIEW

**Comment by kcemenike** [comment]
Hi Ekemini,
Thanks for this.
Can you take a look at the statements in the try block? Do you notice that you're accepting input from the user in the format "%d-%m-%yyyy" but you're trying to convert it using the "%m-%d-%yyyy" format?

This means that if a user enters 12-31-2000 the code will run, but if he enters 31-12-2000 the code will fail.

You may need to correct this.

Cheers

**Comment by EkeminiImeOtu** [comment]
Thank you so much sir, your solution was wonderful and it will help so much
in the assignment given yesterday. Just glad you could see it on my github.

**Review by kcemenike — APPROVED** [review]
This is lovely!!!

Good job

**Comment by EkeminiImeOtu** [comment]
Thank you so much sir, looking forward to learning and solving more
problems. God bless you for the sacrifices.

**Pull request merged**
