### PR TITLE
Create ekeminiOtu

### PR DESCRIPTION
**Pull request by EkeminiImeOtu**
my assignment

### CODE REVIEW

**Comment by EkeminiImeOtu** [comment]
Just hoping I got it right with the whole github process.

**Comment by kcemenike** [comment]
image
Looks like you have attempted to create a pull request to 'master' instead of 'ekemini' branch.
Can you try again, this time, selecting the 'ekemini' branch like so
image
Then send the pull request again.

Thanks a lot sir

**Comment by kcemenike** [comment]
You're doing great bro.

This is exactly what happens in collaborated projects. So it's not out of place to gain this experience, because soon you will be working with bad ass devs from across the world too :-)


I'm on whatsapp 08034381517 if you need to chat there too

Kelechi


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by EkeminiImeOtu** [comment]
Thank you sir for the encouragement. It is really frustrating using github
right now but i know i will get better. Thank you for your patience.
I just dont want to miss out submitting this assignment. I have tried to
come out with a possible solution after trying and failing.

https://github.com/EkeminiImeOtu/task.git

**Pull request closed without merging**
