### PR TITLE
Create Pauline Datetime2.txt

### PR DESCRIPTION
**Pull request by Abhulimen**

### CODE REVIEW

**Comment by kcemenike** [comment]
Hi Pauline, 
Can you save your assignment in a py file instead of in a txt file?

Thanks,
Kelechi

**Comment by Abhulimen** [comment]
Okay Sir. I already did but unable to find the branch you created for me
anymore

**Comment by kcemenike** [comment]
closing this pull request, as I believe it has been resolved

**Review by kcemenike — COMMENTED** [review]
I think you should try to run this python file, you would notice that it returns an error. 

Please review and resend

**Comment by Abhulimen** [comment]
I guess it's because I had the question pasted before the solution. It's
settled. I'll try resending it, I hope I find my branch you created still.

**Pull request closed without merging**
